import type { MetadataRoute } from 'next';

// Served at /manifest.webmanifest. iOS ignores SVG icons, so PNGs (generated by
// scripts/gen-icons.mjs) are listed alongside the SVG that Chromium/Android honor.
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/',
    name: 'AllSet CRM',
    short_name: 'AllSet',
    display: 'standalone',
    start_url: '/',
    background_color: '#070d18',
    theme_color: '#070d18', // dark is the default theme (decision 2026-07-07)
    icons: [
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
